### ISSUE TITLE
BE: Prospects Model + API CRUD operations

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-marinara#16]
- one user will have many prospects
- prospects -> email, status (open, responded, unsubscribed), **first name, last name**
- The routes below are protected via JWT token (middleware or decorator):
      - API to get all prospects for a user 
      - API route to create a list of prospects (think about the CSV import) for a user (takes a CSV file from a multi-form upload) - you will also need to consider mapping columns in the CSV to fields on the prospect model 
      - API route to delete and update prospect

**Comment by skassam21** [comment]
Split this ticket into two PRs:
- prospects model + get, delete, update prospect
- jwt middleware, authentication
- create from a list of prospects (CSV uplaoding back-end)

**Comment by airensurzyn** [comment]
The scope of this Issue will be : 

- Create an API model for Prospect
prospects -> email, status (open, responded, unsubscribed), first name, last name

- Add Endpoints for Basic CRUD operations
