### ISSUE TITLE
FE: Navbar in the logged in user component

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-marinara#19]
- One navbar used throughout the whole logged in user experience (navbar is properly styled and shows a placeholder image for the user)
- The dropdown for the profile in the navbar should just show two links - logout (add logout functionality), + edit profile (no nothing at the moment)
- click on the navbar and move between different pages (those pages can be blank for now)

**Comment by umbauk** [comment]
Successfully getting token and refresh_token from gmail and saving refresh_token to database.

Next: Test using tokens for gmail operations through API
